Method Chaining and Pipelines

* Method chaining in Pandas means calling multiple DataFrame methods in a single line, like a chain  




*   .pipe() is a special method that lets you inject a function into a method chain.

.assign() - add/modify cols

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({

    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [80, 70, 90],
    'Science': [85, 60, 95]
})

# Add a new column 'Average'
df = df.assign(Average=lambda d: (d['Math'] + d['Science']) / 2)
print(df)

      Name  Math  Science  Average
0    Alice    80       85     82.5
1      Bob    70       60     65.0
2  Charlie    90       95     92.5

.querry() - SQL like Filtering

In [3]:
df.query('Average > 85')

      Name  Math  Science  Average
2  Charlie    90       95     92.5

.pipe() - Apply Custom Changes

In [4]:
def capitalize_names(df):                        #Capiitalize_names defines a custom Python function named
    df['Name'] = df['Name'].str.capitalize()
    return df

df = df.pipe(capitalize_names)
print(df)

      Name  Math  Science  Average
0    Alice    80       85     82.5
1      Bob    70       60     65.0
2  Charlie    90       95     92.5

In [7]:
# example of full .pipe()
df = (
    pd.DataFrame({
    'Name': ['alice', 'BOB', 'ChaRLIE'],
    'Math': [80, 70, 90],
    'Science': [85, 60, 95]
})
    .assign(Average=lambda d: (d['Math'] + d['Science']) / 2)
    .query('Average > 85')
    .pipe(capitalize_names)
)

df

      Name  Math  Science  Average
2  Charlie    90       95     92.5