In [8]:
import pandas as pd
import numpy as np

#sample example

data = {
    'Name': ['alice', 'BOB', 'CharLIE','HeT', 'Rihi'],
    'Maths': [45, 0,77,88,80],
    'Science': [67,55,43,0,99],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female' ]
   }

df = pd.DataFrame(data)

#Clean names (strip and capitalize)

df['Name'] = df['Name'].str.strip().str.capitalize()

#Convert Gender to category

df['Gender'] = df['Gender'].astype('category')

#filling missing score with mean

df[['Maths', 'Science']] = df[['Maths', 'Science']].fillna(df[['Maths', 'Science']].mean())

#Add average score using .assign()

df = df.assign(Average=lambda d: d[['Maths', 'Science']].mean(axis=1))

#Filter high performers using .query()

high_performers = df.query('Average >= 80')

#Group by Gender

group_stats = df.groupby('Gender')['Average'].mean()

#Custom function with .pipe()
def tag_pass_fail(d):
    d['Status'] = np.where(d['Average'] >= 80, 'Pass', 'Fail')
    return d

df = df.pipe(tag_pass_fail)

print("Full Processed DataFrame:\n", df)
print("\nHigh Performers:\n", high_performers)
print("\nGroup Stats:\n", group_stats)

Full Processed DataFrame:
       Name  Maths  Science  Gender  Average Status
0    Alice     45       67  Female     56.0   Fail
1      Bob      0       55    Male     27.5   Fail
2  Charlie     77       43    Male     60.0   Fail
3      Het     88        0    Male     44.0   Fail
4     Rihi     80       99  Female     89.5   Pass

High Performers:
    Name  Maths  Science  Gender  Average
4  Rihi     80       99  Female     89.5

Group Stats:
 Gender
Female    72.750000
Male      43.833333
Name: Average, dtype: float64

<ipython-input-8-d71c836f92c5>:37: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  group_stats = df.groupby('Gender')['Average'].mean()